'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const {CoopConquest,REGIONS,SPECIALS}=require('./coop-conquest.cjs');
const {Battle}=require('../种族战役2复刻/engine.js');
const C=require('../种族战役2复刻/content.js');
const {packet}=require('../联机预研/room-server.cjs');
const {startCoopServer,RULES,PROTOCOL}=require('./coop-room-server.cjs');
const {WebSocket}=require('../联机预研/vendor/ws');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
function start(c){assert.ok(c.command(0,'ready',true));assert.ok(c.command(1,'ready',true));assert.equal(c.phase,'battle');}
function win(c){start(c);if(c.battle.siege)c.battle.siege.score=7500;else c.battle.scores[0]=25;c.step();}
test('adjacent target selection is shared and changing it clears both readiness flags',()=>{const c=new CoopConquest();assert.deepEqual(c.armies.map(a=>a.roster.length),[4,4]);c.command(0,'ready',true);assert.equal(c.command(1,'target',9),false);assert.equal(c.ready[0],true);assert.ok(c.command(1,'target',16));assert.deepEqual(c.ready,[false,false]);assert.equal(c.command(2,'target',19),false);start(c);assert.equal(c.command(0,'target',19),false);assert.ok(c.battle.siege);});
test('every region at all alliance tiers uses at most three races and exactly eight valid troops per row',()=>{for(const stage of [0,3,6,26])for(const r of REGIONS){const c=new CoopConquest();c.stage=stage;c.target=r.id;const l=c.level();assert.equal(l.enemyRaces[0],r.race);assert.ok(l.enemyRaces.length<=Math.min(3,1+Math.floor(stage/3)));assert.equal(new Set(l.enemyRaces).size,l.enemyRaces.length);for(const wave of l.waves){assert.deepEqual(wave.units.map(u=>u.lane),[0,1,2,3,4,5,6,7]);for(const u of wave.units){const race=l.enemyRaces[u.owner-2];assert.ok(C.races[race].roster.includes(u.type));for(const f of C.atlas[race+'-'+u.type].files){assert.ok(fs.existsSync(path.join(__dirname,'../种族战役2复刻/assets',f)));assert.ok(fs.existsSync(path.join(__dirname,'../种族战役2复刻/assets/mobile',f)));}}}}});
test('three-race armies stay on the enemy team, retain race art and never target their allies',()=>{const c=new CoopConquest();c.stage=6;c.target=11;start(c);assert.equal(c.battle.players.length,5);assert.deepEqual(c.battle.options.teams,[0,0,1,1,1]);for(let i=0;i<c.level().waves.length;i++){c.battle.tick=c.nextWaveAt();c.step();}assert.equal(c.battle.players.slice(2).reduce((n,p)=>n+p.spawned,0),c.wave*8);for(const u of c.battle.units){assert.equal(u.race,c.battle.options.races[u.owner]);assert.equal(u.side,1);assert.equal(c.battle.target(u),null);}const snapshot=c.battle.snapshot();assert.deepEqual(Battle.restore(snapshot).snapshot(),snapshot);snapshot.options.teams[4]=0;assert.throws(()=>Battle.restore(snapshot));});
test('castle progress and defense are independent and defense failure wins ties',()=>{const c=new CoopConquest();c.command(0,'target',16);start(c);c.battle.siege.score=7000;c.battle.scores=[24,7];assert.equal(c.view().progress,7000);assert.equal(c.view().defense,43);c.battle.siege.score=7500;c.battle.scores[1]=50;c.step();assert.equal(c.phase,'failed');assert.equal(c.owned.length,1);assert.ok(c.command(1,'retry'));assert.equal(c.target,16);assert.equal(c.battle,null);win(c);assert.equal(c.owned.length,2);assert.deepEqual(c.armies.map(a=>a.gold),[1000,1000]);c.step();assert.equal(c.armies[0].gold,1000);});
test('shared packet preserves siege state and climb and enter poses',()=>{const c=new CoopConquest();c.command(0,'target',16);start(c);const u=c.battle.spawn(1,0,2);u.climbFrame=3;c.battle.siege.ladders[2]=true;const p=packet({battle:c.battle,seats:[]});assert.equal(p.units[0][11],1);assert.equal(p.units[0][13],3);assert.equal(p.units[0][14],0);assert.equal(p.siege.ladders[2],true);});
test('all 27 conquests settle once, preserve distinct player armies, and finish with no target',()=>{const c=new CoopConquest({races:['human','orc2']});let reward=0;while(c.phase!=='complete'){reward+=c.level().reward;win(c);assert.equal(c.stage,c.owned.length-1);assert.deepEqual(CoopConquest.restore(c.snapshot()).snapshot(),c.snapshot());}assert.equal(c.owned.length,28);assert.equal(c.target,null);assert.deepEqual(c.armies.map(a=>a.gold),[500+reward,500+reward]);assert.ok(c.armies[1].roster.includes(11));assert.equal(c.command(1,'ready',true),false);});
test('multi-race conquest resumes deterministically and rejects altered ownership and disconnected regions',()=>{const c=new CoopConquest();for(let i=0;i<6;i++)win(c);c.target=11;start(c);for(let i=0;i<700;i++)c.step();const restored=CoopConquest.restore(c.snapshot());for(let i=0;i<300;i++){c.step();restored.step();}assert.deepEqual(c.snapshot(),restored.snapshot());const bad=c.snapshot();bad.battle.options.races[0]='elf';assert.throws(()=>CoopConquest.restore(bad));const dis=new CoopConquest().snapshot();dis.owned.push(9);dis.stage=1;assert.throws(()=>CoopConquest.restore(dis));});
test('waves never end early and no clock limit auto-wins a conquest',()=>{const c=new CoopConquest();start(c);for(let n=0;n<15;n++){c.battle.tick=c.nextWaveAt();c.step();c.battle.units=[];c.battle.projectiles=[];}assert.equal(c.wave,15);c.battle.tick=24*601;c.step();assert.equal(c.phase,'battle');assert.equal(c.view().progress,0);});
async function peer(port){const ws=new WebSocket(`ws://127.0.0.1:${port}`),q=[],waiters=[];ws.on('message',raw=>{const m=JSON.parse(raw),i=waiters.findIndex(w=>w.f(m));if(i<0)q.push(m);else{const w=waiters.splice(i,1)[0];clearTimeout(w.timer);w.resolve(m);}});await new Promise((yes,no)=>{ws.once('open',yes);ws.once('error',no);});return {ws,send:m=>ws.send(JSON.stringify(m)),next(f){const i=q.findIndex(f);if(i>=0)return Promise.resolve(q.splice(i,1)[0]);return new Promise((resolve,reject)=>{const w={f,resolve,timer:setTimeout(()=>reject(Error('network timeout')),3000)};waiters.push(w);});}};}
async function network(){const s=await startCoopServer({port:0,manual:true}),peers=[];try{
 const a=await peer(s.port),b=await peer(s.port);peers.push(a,b);a.send({type:'create',race:'human',mode:'conquest',rules:RULES,protocol:PROTOCOL});const welcome=await a.next(m=>m.type==='welcome');b.send({type:'join',room:welcome.room,race:'demon',rules:RULES,protocol:PROTOCOL});await b.next(m=>m.type==='welcome');let seqA=0,seqB=0;
 async function cmd(p,action,value){const seq=p===a?++seqA:++seqB;p.send({type:'command',seq,action,value});return p.next(m=>m.type==='ack'&&m.seq===seq);}
 const r=s.rooms.get(welcome.room);assert.equal(r.campaign.mode,'conquest');assert.ok((await cmd(a,'ready',true)).ok);assert.ok((await cmd(b,'target',16)).ok);await a.next(m=>m.type==='coopState'&&m.campaign.map?.target===16&&!m.campaign.ready[0]);assert.deepEqual(r.campaign.ready,[false,false]);
 assert.ok((await cmd(a,'ready',true)).ok);assert.ok((await cmd(b,'ready',true)).ok);const battle=await b.next(m=>m.type==='coopState'&&m.campaign.phase==='battle');assert.equal(battle.siege.target,7500);assert.equal(battle.battleConfig.races[2],'undead');s.advance(100);assert.equal(r.campaign.battle.tick,0);
 for(const p of peers)p.send({type:'loaded',round:r.round});await b.next(m=>m.type==='coopState'&&m.campaign.phase==='battle'&&m.loaded.every(Boolean));s.advance(200);assert.equal(r.campaign.battle.players[2].spawned,8);
 // A long-running, connected battle must outlive the old one-hour hard limit.
 r.created=performance.now()-3600001;s.sweep();assert.ok(s.rooms.has(r.code));
 r.campaign.battle.siege.score=7500;s.advance();const settled=await a.next(m=>m.type==='coopState'&&m.campaign.map?.owned.includes(16));assert.equal(settled.campaign.phase,'shop');assert.equal(settled.campaign.armies[1].gold,1000);assert.deepEqual(settled.campaign.ready,[false,false]);
 console.log('PASS real two-client conquest target sync, readiness invalidation, siege load barrier, reward and active-room lifetime');count++;
 }finally{for(const p of peers)p.ws.terminate();await s.close();}}
network().then(()=>console.log(`${count} conquest checks passed.`)).catch(e=>{console.error(e);process.exitCode=1;});
