 'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {CoopCampaign,LEVELS}=require('./coop-campaign.cjs'),{startCoopServer,RULES,PROTOCOL}=require('./coop-room-server.cjs'),{WebSocket}=require('../联机预研/vendor/ws');
const C=require('../种族战役2复刻/content.js');
let count=0;function test(name,fn){fn();console.log('PASS '+name);count++;}
function start(c){c.command(0,'ready',true);assert.equal(c.phase,'shop');c.command(1,'ready',true);assert.equal(c.phase,'battle');}
test('separate gold, owner-scoped purchases and both-ready barrier',()=>{const c=new CoopCampaign();assert.deepEqual(c.armies.map(a=>a.gold),[500,500]);assert.ok(c.command(0,'buyUpgrade',{unit:0,upgrade:0}));assert.deepEqual(c.armies.map(a=>a.gold),[200,500]);assert.equal(c.command(1,'buyUnit',32),false);start(c);assert.deepEqual(c.battle.options.teams,[0,0,1]);assert.equal(c.command(0,'buyUnit',7),false);});
test('first wave fills eight lanes at the configured tick',()=>{const c=new CoopCampaign();start(c);for(let i=0;i<LEVELS[0].firstWaveAt;i++)c.step();assert.equal(c.battle.players[2].spawned,0);c.step();assert.equal(c.battle.players[2].spawned,8);assert.deepEqual(c.battle.units.map(u=>u.lane).sort(),[0,1,2,3,4,5,6,7]);});
test('waves repeat beyond their unit sequence and a clear battlefield is not victory',()=>{const c=new CoopCampaign();start(c);for(let n=0;n<13;n++){c.battle.tick=c.nextWaveAt();c.step();assert.equal(c.wave,n+1);assert.equal(c.battle.players[2].spawned,8*(n+1));c.battle.units=[];c.battle.projectiles=[];c.step();assert.equal(c.phase,'battle');}assert.equal(c.view().progress,0);});
test('allied progress is independent of enemy defense damage and has no timer win',()=>{const c=new CoopCampaign();start(c);c.battle.scores=[12,4];assert.equal(c.view().progress,12);assert.equal(c.view().defense,46);c.battle.scores[1]=20;assert.equal(c.view().progress,12);assert.equal(c.view().defense,30);c.battle.tick=24*600;c.step();assert.equal(c.phase,'battle');assert.equal(c.view().progress,12);assert.equal(c.view().progressMax,25);});
test('reaching the progress target pays once and preserves both-ready shop barrier',()=>{const c=new CoopCampaign();start(c);c.battle.scores=[24,49];c.step();assert.equal(c.phase,'battle');c.battle.scores[0]=25;c.step();assert.equal(c.phase,'shop');assert.equal(c.stage,1);assert.deepEqual(c.armies.map(a=>a.gold),[1000,1000]);for(let i=0;i<100;i++)c.step();assert.deepEqual(c.armies.map(a=>a.gold),[1000,1000]);c.command(0,'ready',true);c.command(0,'buyUnit',3);assert.equal(c.ready[0],false);c.command(1,'ready',true);assert.equal(c.phase,'shop');c.command(0,'ready',true);assert.equal(c.phase,'battle');assert.equal(c.view().progress,0);assert.equal(c.view().defense,50);});
test('defense reaching zero fails, including simultaneous final breakthroughs',()=>{for(const score of [10,25]){const c=new CoopCampaign();start(c);c.battle.scores=[score,50];c.step();assert.equal(c.phase,'failed');assert.equal(c.lastResult.reward,0);assert.deepEqual(c.armies.map(a=>a.gold),[500,500]);}});
test('natural undefended defeat and retry keep purchases but reset progress',()=>{const c=new CoopCampaign();c.command(0,'buyUpgrade',{unit:0,upgrade:0});start(c);for(let i=0;i<10000&&c.phase==='battle';i++)c.step();assert.equal(c.phase,'failed');assert.deepEqual(c.armies.map(a=>a.gold),[200,500]);assert.ok(c.command(1,'retry'));start(c);assert.equal(c.wave,0);assert.equal(c.view().progress,0);assert.equal(c.view().defense,50);assert.ok(c.battle.has(0,0,0));});
test('checkpoint beyond eight waves restores repeated schedule and independent progress',()=>{const c=new CoopCampaign();start(c);c.battle.tick=2400;c.step();assert.ok(c.wave>8);c.battle.scores=[9,7];const r=CoopCampaign.restore(c.snapshot());for(let i=0;i<400;i++){c.step();r.step();}assert.deepEqual(c.snapshot(),r.snapshot());});
test('every stage uses valid race units, continuous schedules and shop rewards',()=>{const c=new CoopCampaign();for(const level of LEVELS){assert.ok(level.waveInterval>=24*6&&level.waveInterval<=24*9);for(const wave of level.waves)assert.ok(C.races[level.enemyRace].roster.includes(wave.type));start(c);c.battle.scores[0]=level.target;c.step();}assert.equal(c.phase,'complete');assert.deepEqual(c.armies.map(a=>a.gold),[2450,2450]);});
test('bounded normal-combat simulations keep scores valid and award only actual victories',()=>{const records=[];for(let stage=0;stage<LEVELS.length;stage++){const c=new CoopCampaign();c.stage=stage;start(c);for(let i=0;i<24*600&&c.phase==='battle';i++){c.battle.ai(0);c.battle.ai(1);c.step();}assert.ok(c.battle.scores.every(x=>Number.isSafeInteger(x)&&x>=0));assert.equal(c.view().progressMax,25);if(c.lastResult){assert.equal(c.lastResult.victory,c.battle.scores[0]>=25&&c.battle.scores[1]<50);assert.deepEqual(c.armies.map(a=>a.gold),[500+c.lastResult.reward,500+c.lastResult.reward]);}records.push({stage,phase:c.phase,seconds:c.battle.tick/24,scores:c.battle.scores,waves:c.wave});}fs.writeFileSync(path.join(__dirname,'simulation-results.json'),JSON.stringify({note:'Unupgraded allied AI baseline; not a claim that bots win or that human balance is final.',records},null,2));});
async function peer(port){const ws=new WebSocket(`ws://127.0.0.1:${port}`),queue=[],waiters=[];ws.on('message',raw=>{const m=JSON.parse(raw),i=waiters.findIndex(w=>w.f(m));if(i>=0){const w=waiters.splice(i,1)[0];clearTimeout(w.timer);w.resolve(m);}else queue.push(m);});await new Promise((resolve,reject)=>{ws.once('open',resolve);ws.once('error',reject);});return {ws,send:m=>ws.send(JSON.stringify({protocol:PROTOCOL,...m})),next(f){const i=queue.findIndex(f);if(i>=0)return Promise.resolve(queue.splice(i,1)[0]);return new Promise((resolve,reject)=>{const w={f,resolve,timer:setTimeout(()=>reject(Error('network timeout')),3000)};waiters.push(w);});}};}
async function network(){const s=await startCoopServer({port:0,manual:true}),peers=[];try{const a=await peer(s.port),b=await peer(s.port);peers.push(a,b);a.send({type:'create',rules:RULES,race:'human'});const wa=await a.next(m=>m.type==='welcome');b.send({type:'join',rules:RULES,room:wa.room,race:'elf'});const wb=await b.next(m=>m.type==='welcome');assert.equal(wb.owner,1);
 async function cmd(p,seq,action,value,owner){p.send({type:'command',seq,action,value,owner});return p.next(m=>m.type==='ack'&&m.seq===seq);}
 assert.ok((await cmd(a,1,'buyUpgrade',{unit:0,upgrade:0},1)).ok);const r=s.rooms.get(wa.room);assert.deepEqual(r.campaign.armies.map(a=>a.gold),[200,500]);assert.equal((await cmd(a,1,'buyUpgrade',{unit:0,upgrade:0})).reason,'duplicate');assert.ok((await cmd(a,2,'ready',true)).ok);assert.equal(r.campaign.phase,'shop');assert.ok((await cmd(b,1,'ready',true)).ok);s.advance(100);assert.equal(r.campaign.battle.tick,0);a.send({type:'loaded',round:r.round});await a.next(m=>m.type==='coopState'&&m.loaded[0]&&!m.loaded[1]);s.advance(100);assert.equal(r.campaign.battle.tick,0);b.send({type:'loaded',round:r.round});await b.next(m=>m.type==='coopState'&&m.loaded.every(Boolean)&&m.round===r.round);s.advance(100);await cmd(a,3,'send');await cmd(b,2,'send');assert.ok(r.campaign.battle.units.filter(u=>u.owner<2).every(u=>u.side===0&&u.dir===1));assert.ok(r.campaign.battle.units.some(u=>u.race==='human'));assert.ok(r.campaign.battle.units.some(u=>u.race==='elf'));
 assert.ok((await cmd(a,4,'pause',true)).ok);s.advance(50);assert.equal(r.campaign.battle.tick,100);assert.equal((await cmd(a,5,'send')).ok,false);assert.ok((await cmd(b,3,'pause',false)).ok);
 const closed=new Promise(resolve=>b.ws.once('close',resolve));b.ws.close();await closed;await a.next(m=>m.type==='coopState'&&m.connected[1]===false&&m.tick===100);const tick=r.campaign.battle.tick;s.advance(200);assert.equal(r.campaign.battle.tick,tick);
 const reconnect=await peer(s.port);peers.push(reconnect);reconnect.send({type:'resume',rules:RULES,room:wa.room,token:wb.token});assert.equal((await reconnect.next(m=>m.type==='welcome')).owner,1);const resume=await reconnect.next(m=>m.type==='coopState');assert.equal(resume.campaign.phase,'battle');assert.equal(resume.tick,tick);s.advance(3);assert.equal(r.campaign.battle.tick,tick);reconnect.send({type:'loaded',round:r.round});await reconnect.next(m=>m.type==='coopState'&&m.loaded.every(Boolean));s.advance(3);assert.equal(r.campaign.battle.tick,tick+3);console.log('PASS real two-client cooperative room, purchase authority, same-side spawning, asset barrier, shared pause and reconnection');count++;}
 finally{for(const p of peers)p.ws.terminate();await s.close();}}
network().then(()=>console.log(`${count} cooperative campaign/network checks passed.`)).catch(e=>{console.error(e);process.exitCode=1;});
