'use strict';
const assert=require('node:assert/strict'),{CoopEndless,POOL,pacing,BASIC,MID,ELITE,MONSTERS,SIEGE}=require('./coop-endless.cjs'),C=require('../种族战役2复刻/content'),{startCoopServer,RULES,PROTOCOL}=require('./coop-room-server.cjs'),{WebSocket}=require('../联机预研/vendor/ws');
const P=require('../种族战役2复刻/progression');
const merc=new CoopEndless({races:['human','elf']});
assert(!merc.command(0,'buyUnit',31));merc.wave=14;assert(!merc.command(0,'buyUnit',31));merc.wave=15;
assert(merc.command(0,'ready',true));assert(merc.command(0,'buyUnit',31));assert.equal(merc.ready[0],false);assert.equal(merc.armies[0].gold,1200);assert.equal(P.unitRace(merc.armies[0],31),'human2');
assert(!merc.command(0,'buyUnit',31));assert(!merc.command(0,'buyUnit',104));assert(!P.buyUnit(P.createArmy('human',9999),31));
assert(merc.command(0,'dismiss',31));assert.equal(merc.armies[0].gold,2100);assert(merc.command(0,'buyUnit',31));
assert(merc.command(1,'buyUnit',100));assert.equal(merc.armies[1].gold,600);assert.equal(P.unitPrice(merc.armies[0],100),1200);
for(const a of merc.armies)a.gold=10000;
const upgrade=Object.values(C.upgrades).find(u=>u.supported&&P.eligible('human2',31,u.id));assert(merc.command(0,'buyUpgrade',{unit:31,upgrade:upgrade.id}));
merc.command(0,'ready',true);merc.command(1,'ready',true);merc.battle.spawn(0,31,3);merc.battle.spawn(1,100,3);assert.equal(merc.battle.units[0].race,'human2');assert.equal(merc.battle.units[1].race,'human');assert(merc.battle.units.every(u=>u.side===0));
const mercCopy=CoopEndless.restore(merc.snapshot());for(let i=0;i<300;i++){merc.step();mercCopy.step();}assert.deepEqual(merc.snapshot(),mercCopy.snapshot());
for(const race of Object.keys(C.races)){const a={...P.createArmy(race,99999),mercenaries:true};for(const id of P.recruitRoster(a)){const skin=P.unitRace(a,id);assert(C.atlas[skin+'-'+id]);assert(require('node:fs').existsSync(require('node:path').join(__dirname,'../种族战役2复刻/assets',`icon-${skin}-${id}.png`)));}}
console.log('PASS mercenaries: double price, native price, refund, funds, no duplicates, readiness reset, original race upgrades/art, allied ownership and deterministic restore');
function start(){const c=new CoopEndless({races:['persian','elf'],seed:918});c.command(0,'ready',true);assert.equal(c.phase,'shop');c.command(1,'ready',true);return c;}
for(const single of [false,true]){
 const health=new CoopEndless({solo:single});health.begin();health.nextAt=1e8;
 const cross=(owner,count=1)=>{health.battle.units=[];for(let i=0;i<count;i++){const u=health.battle.spawn(owner,0,i%8,owner<2?1451:-1451);u.frame=C.units[0].labels.walk;}health.step();};
 cross(2,30);assert.equal(health.view().defense,20);cross(0);assert.equal(health.view().defense,21);cross(single?0:1);assert.equal(health.view().defense,22);
 for(let i=0;i<12;i++)health.step();assert.equal(health.view().defense,22,'exit runners heal only once');
 cross(0,60);assert.equal(health.view().defense,50);cross(2);assert.equal(health.view().defense,49,'overhealing at full cannot shield a future breakthrough');
 health.battle.units=[];for(const owner of [0,2]){const u=health.battle.spawn(owner,0,owner,owner===0?1451:-1451);u.frame=C.units[0].labels.walk;}health.step();assert.equal(health.view().defense,49,'same-tick opposing breakthroughs cancel');
 const saved=health.snapshot(),copy=CoopEndless.restore(saved);for(let i=0;i<30;i++){health.step();copy.step();}assert.deepEqual(health.snapshot(),copy.snapshot());assert.equal(copy.view().defense,49);
 const old=health.snapshot();delete old.defense;delete old.defenseScores;const migrated=CoopEndless.restore(old);assert.equal(migrated.view().defense,18);migrated.step();assert.equal(migrated.view().defense,18,'old breakthroughs are not credited again');
 for(const defense of [-1,51,2.5,null]){const bad=health.snapshot();bad.defense=defense;assert.throws(()=>CoopEndless.restore(bad));}const bad=health.snapshot();bad.defenseScores[0]--;assert.throws(()=>CoopEndless.restore(bad));
 health.wave=10;health.shopOffer={wave:10,reward:1000,votes:[false,false]};health.command(0,'shopVote',true);if(!single)health.command(1,'shopVote',true);assert.equal(health.phase,'shop');assert.equal(CoopEndless.restore(health.snapshot()).view().defense,49);health.step();health.command(0,'ready',true);if(!single)health.command(1,'ready',true);assert.equal(health.view().defense,49);
 cross(2,49);assert.equal(health.phase,'failed');assert.equal(health.view().defense,0);health.command(0,'retry');health.command(0,'ready',true);if(!single)health.command(1,'ready',true);assert.equal(health.view().defense,50);
}
console.log('PASS endless defense: actual allied breakthroughs heal, enemy breakthroughs hurt, shared/solo behavior, cap, no banked healing, simultaneous exits, save migration, shop resume and defeat/retry');
assert.deepEqual(new Set(POOL.map(u=>u.type)),new Set(C.order.filter(id=>(id<101||id>104)&&!C.units[id].playerOnly&&!C.units[id].summonOnly)));for(const u of POOL)assert(C.races[u.race].roster.includes(u.type));
const c=start();assert.deepEqual(c.armies.map(a=>a.gold),[3000,3000]);assert(c.battle.options.teams.slice(2).every(t=>t===1));const seen=new Set();
for(let i=0;i<120;i++){c.battle.tick=c.nextWaveAt();c.step();for(const u of c.battle.units){assert.equal(u.side,1);assert(C.races[u.race].roster.includes(u.type));seen.add(u.type);}c.battle.units=[];c.battle.projectiles=[];}
assert.deepEqual(seen,new Set(C.order.filter(id=>(id<101||id>104)&&!C.units[id].playerOnly&&!C.units[id].summonOnly)));c.battle.scores=[0,49];c.step();assert.equal(c.phase,'battle');assert.equal(c.view().defense,1);assert.equal(c.view().progressMax,null);
c.battle.scores[0]=99999;c.step();assert.equal(c.view().defense,50);c.battle.scores[1]+=49;c.step();assert.equal(c.view().defense,1);
const restored=CoopEndless.restore(c.snapshot());for(let i=0;i<180;i++){c.step();restored.step();}assert.deepEqual(c.snapshot(),restored.snapshot());c.battle.scores[1]++;c.step();assert.equal(c.phase,'failed');assert.equal(c.view().defense,0);assert.equal(c.lastResult.victory,false);assert(c.command(0,'retry'));c.command(0,'ready',true);c.command(1,'ready',true);assert.equal(c.wave,0);assert.equal(c.view().defense,50);
for(let seed=1;seed<=20;seed++){const paced=new CoopEndless({seed});paced.command(0,'ready',true);paced.command(1,'ready',true);for(let wave=1;wave<=60;wave++){paced.battle.tick=paced.nextAt;const tick=paced.battle.tick;paced.step();const spawned=paced.battle.units;assert.equal(spawned.length,pacing(wave).count);assert.equal(paced.nextAt-tick,pacing(wave).seconds*24);assert(spawned.filter(u=>!BASIC.includes(u.type)).length<=pacing(wave).special);if(wave<=15)assert(spawned.every(u=>BASIC.includes(u.type)));else if(wave<=25)assert(spawned.every(u=>BASIC.includes(u.type)||MID.includes(u.type)));paced.battle.units=[];paced.battle.projectiles=[];}}
console.log('PASS gentler pacing: 20 seeds, 60 waves each, basic-only through wave 15, capped specialist slots, heavy units withheld through wave 25, longer intervals');
const adaptive=start();assert(!adaptive.battle.options.races.slice(2).includes('persian'));assert(POOL.every(u=>u.race!=='persian'&&![101,102,103,104].includes(u.type)));
function sample(losses,breaks,kills=0){adaptive.battle.scores[1]+=losses;adaptive.battle.scores[0]+=breaks;adaptive.battle.players[0].kills+=kills;adaptive.battle.tick=adaptive.director.nextTick;adaptive.adapt();}
sample(4,20);assert.equal(adaptive.director.pressure,-2);sample(5,0);assert.equal(adaptive.director.pressure,-2);assert.equal(adaptive.wavePlan(5).special,0);assert(adaptive.wavePlan(5).seconds>pacing(5).seconds);
sample(0,20);assert.equal(adaptive.director.pressure,-2,'relief lasts 30 seconds despite breakthroughs');sample(0,0);assert.equal(adaptive.director.pressure,-1);sample(0,0);assert.equal(adaptive.director.pressure,0);
for(let i=0;i<9;i++)sample(0,8);assert.equal(adaptive.director.pressure,6);assert.equal(adaptive.wavePlan(15).special,0);assert.equal(adaptive.wavePlan(16).special,1);assert(adaptive.wavePlan(30).seconds<pacing(30).seconds);
adaptive.wave=200;adaptive.nextAt=adaptive.director.nextTick+96;const beforeCountdown=adaptive.nextAt;sample(4,20);assert.equal(adaptive.director.pressure,0,'severe damage immediately removes maximum pressure');assert(adaptive.nextAt>beforeCountdown,'relief extends the remaining countdown');
adaptive.battle.scores[1]+=35;adaptive.syncDefense();sample(1,0);assert.equal(adaptive.director.pressure,-2);sample(0,20);assert.equal(adaptive.director.pressure,-2);for(let i=0;i<10;i++)sample(0,8);assert.equal(adaptive.director.pressure,6,'low defense alone must not lock difficulty down forever');
const ac=CoopEndless.restore(adaptive.snapshot());assert.deepEqual(ac.director,adaptive.director);for(let i=0;i<120;i++){adaptive.step();ac.step();}assert.deepEqual(ac.snapshot(),adaptive.snapshot());
const legacy=adaptive.snapshot();legacy.director.pressure=2;delete legacy.director.kills;delete legacy.director.safeSamples;delete legacy.director.reliefUntil;const migrated=CoopEndless.restore(legacy);assert.equal(migrated.director.kills,adaptive.battle.players[0].kills);assert.equal(migrated.director.safeSamples,0);assert.equal(migrated.director.reliefUntil,0);
adaptive.phase='shop';const unchanged=structuredClone(adaptive.director);adaptive.step();assert.deepEqual(adaptive.director,unchanged);
const holding=start();holding.wave=200;for(let i=0;i<8;i++){holding.battle.tick=holding.director.nextTick;holding.battle.players[i%2].kills+=8;holding.nextAt=holding.battle.tick+96;holding.adapt();if(i===0)assert.equal(holding.director.pressure,0);if(i===1)assert(holding.nextAt<holding.battle.tick+96);}assert.equal(holding.director.pressure,6,'sustained safe kills increase difficulty without breakthroughs');assert.equal(holding.wavePlan(201).seconds,1.5);
for(let i=0;i<6;i++){holding.battle.spawn(2,0,i);holding.battle.units.at(-1).x=-750;}holding.battle.tick=holding.director.nextTick;holding.adapt();assert.equal(holding.director.pressure,5,'enemies near defense prevent further escalation');
console.log('PASS adaptive difficulty: safe kills and breakthroughs raise pressure to 6, damage relief is immediate/temporary, low-health recovery, live countdown, old saves, deterministic restore and shop pause');
for(let seed=1;seed<=12;seed++)for(const pressure of [-2,0,2,6]){
 const late=new CoopEndless({seed});late.begin();late.director.pressure=pressure;late.director.nextTick=1e8;
 for(const wave of [81,85,100,101,150,151,199,200,201,205,210,250,351,501]){
  late.wave=wave-1;late.battle.tick=late.nextAt;const tick=late.battle.tick,plan=late.wavePlan(wave);late.step();const row=late.battle.units;
  assert.equal(row.length,8);assert.equal(new Set(row.map(u=>u.lane)).size,8);assert.equal(new Set(row.map(u=>u.type)).size,1);assert(row.every(u=>!BASIC.includes(u.type)&&u.race!=='persian'));
  const tier={elite:ELITE,siege:SIEGE,monster:MONSTERS}[plan.formation];assert(row.every(u=>tier.includes(u.type)));assert.equal(late.nextAt-tick,plan.seconds*24);
  if(pressure===6&&wave>=151)assert.equal(plan.seconds,1.5);if(pressure===6&&wave===200)assert.equal(plan.formation,'monster');if(pressure===6&&wave===201)assert.equal(plan.formation,'elite');if(pressure===6&&wave===205)assert.equal(plan.formation,'siege');
  late.battle.units=[];late.battle.projectiles=[];
 }
}
assert.equal(pacing(201).seconds,4);assert.equal(pacing(351).seconds,2.5);
const capped=start();capped.wave=199;capped.battle.tick=capped.nextAt;capped.director.nextTick=1e8;for(let i=0;i<380;i++)capped.battle.spawn(2,0,i%8);const gold=capped.armies[0].gold;capped.step();assert.equal(capped.wave,199);assert.equal(capped.rewardTotal,0);assert.equal(capped.armies[0].gold,gold);assert.equal(capped.battle.units.length,380);capped.battle.units.splice(0,4);capped.battle.tick=capped.nextAt;capped.step();assert.equal(capped.wave,200);assert.equal(capped.battle.units.length,384);assert.equal(capped.armies[0].gold,gold+1000);
const lateSolo=new CoopEndless({solo:true});lateSolo.begin();lateSolo.director.pressure=6;lateSolo.director.nextTick=1e8;for(const wave of [200,201,205]){lateSolo.wave=wave-1;lateSolo.battle.tick=lateSolo.nextAt;lateSolo.step();assert.equal(lateSolo.battle.units.length,4);assert.equal(new Set(lateSolo.battle.units.map(u=>u.lane)).size,4);lateSolo.battle.units=[];lateSolo.battle.projectiles=[];}
console.log('PASS late endless: 12 seeds across 4 pressure levels, 8-lane elite/siege/monster rows, 1.5s dominance cadence, solo half rows and no empty-wave rewards at cap');
const solo=new CoopEndless({solo:true,seed:9});assert(!solo.command(1,'ready',true));assert(solo.command(0,'ready',true));assert.equal(solo.phase,'battle');let doubleCount=0,soloCount=0;for(let wave=1;wave<=80;wave++){solo.battle.tick=solo.nextAt;doubleCount+=solo.wavePlan(wave).count;solo.step();soloCount+=solo.battle.units.length;assert.equal(soloCount,Math.floor(doubleCount/2));assert(solo.battle.units.every(u=>u.side===1&&u.race!=='persian'));solo.battle.units=[];solo.battle.projectiles=[];}const soloCopy=CoopEndless.restore(solo.snapshot());assert.equal(soloCopy.solo,true);solo.command(0,'shopVote',true);assert.equal(solo.phase,'shop');solo.command(0,'ready',true);assert.equal(solo.phase,'battle');assert.equal(solo.wave,80);assert.deepEqual(soloCopy.director,solo.director);console.log('PASS solo endless: one-player start/shop, second commander rejected, exact cumulative half spawns over 80 waves, checkpoint');
const noDefense=start();for(let i=0;i<18000&&noDefense.phase==='battle';i++)noDefense.step();assert.equal(noDefense.phase,'failed');
const supply=start();supply.armies[0].gold=10000;assert(P.buyUnit(supply.armies[0],31));supply.begin();supply.battle.spawn(0,31,3);supply.wave=9;supply.battle.tick=supply.nextAt;supply.step();assert.equal(supply.shopOffer.wave,10);assert.equal(supply.armies[1].gold,4000);assert(supply.command(0,'shopVote',true));assert.equal(supply.phase,'battle');assert(supply.command(1,'shopVote',true));assert.equal(supply.phase,'shop');const tick=supply.battle.tick,units=structuredClone(supply.battle.units),scores=supply.battle.scores.slice();supply.step();assert.equal(supply.battle.tick,tick);assert(supply.command(0,'dismiss',31));assert(supply.command(0,'buyUnit',8));assert.equal(CoopEndless.restore(supply.snapshot()).intermission,true);supply.command(0,'ready',true);supply.command(1,'ready',true);assert.equal(supply.battle.tick,tick);assert.deepEqual(supply.battle.units,units);assert.deepEqual(supply.battle.scores,scores);assert(!supply.battle.roster(0).includes(31));assert(supply.battle.roster(0).includes(8));const supplyCopy=CoopEndless.restore(supply.snapshot());for(let i=0;i<100;i++){supply.step();supplyCopy.step();}assert.deepEqual(supply.snapshot(),supplyCopy.snapshot());assert.equal(supply.armies[1].gold,4000);supply.wave=19;supply.battle.tick=supply.nextAt;supply.step();assert.equal(supply.shopOffer.wave,20);assert(supply.command(0,'shopVote',false));assert.equal(supply.shopOffer,null);assert.equal(supply.phase,'battle');
const unlock=start();unlock.wave=14;unlock.battle.tick=unlock.nextAt;const beforeGold=unlock.armies[0].gold;unlock.step();assert.equal(unlock.shopOffer.wave,15);assert.equal(unlock.shopOffer.reward,0);assert.equal(unlock.armies[0].gold,beforeGold);assert.equal(CoopEndless.restore(unlock.snapshot()).shopOffer.wave,15);unlock.command(0,'shopVote',true);unlock.command(1,'shopVote',true);assert(unlock.command(0,'buyUnit',31));console.log('PASS foreign unlock: rejected at waves 0/14, available at 15, shared shop invitation and no extra reward');
console.log('PASS supply: tenth-wave reward once, mutual votes, paused shop, sell keeps deployed troops, resume keeps battle and restore, skip and recurring offer');
console.log('PASS endless: all unit types/race art, teams, infinite breakthroughs, shared defense, deterministic restore, retry and natural defeat');
async function peer(port){const ws=new WebSocket(`ws://127.0.0.1:${port}`),q=[],wait=[];ws.on('message',r=>{const m=JSON.parse(r),i=wait.findIndex(w=>w.f(m));if(i<0)q.push(m);else{const w=wait.splice(i,1)[0];clearTimeout(w.t);w.y(m);}});await new Promise((y,n)=>{ws.once('open',y);ws.once('error',n);});return {ws,send:m=>ws.send(JSON.stringify({rules:RULES,protocol:PROTOCOL,...m})),next(f){const i=q.findIndex(f);if(i>=0)return Promise.resolve(q.splice(i,1)[0]);return new Promise((y,n)=>{const w={f,y,t:setTimeout(()=>n(Error('timeout')),3000)};wait.push(w);});}};}
(async()=>{const s=await startCoopServer({port:0,manual:true}),peers=[];try{
 const a=await peer(s.port),b=await peer(s.port);peers.push(a,b);a.send({type:'auto',mode:'endless',race:'human'});b.send({type:'auto',mode:'endless',race:'persian'});const [wa,wb]=await Promise.all([a.next(m=>m.type==='welcome'),b.next(m=>m.type==='welcome')]);assert.equal(wa.room,wb.room);assert.equal(s.rooms.size,1);assert.notEqual(wa.owner,wb.owner);const r=s.rooms.get(wa.room);assert.equal(r.campaign.mode,'endless');assert.equal(r.campaign.armies[wb.owner].race,'persian');assert.equal(r.campaign.armies[1].gold,3000);assert.equal(r.campaign.armies[1].mercenaries,true);assert.equal(s.rooms.get(wa.room).campaign.armies[0].mercenaries,true);
 for(const p of [a,b])p.send({type:'command',seq:1,action:'ready',value:true});await Promise.all([a.next(m=>m.type==='ack'),b.next(m=>m.type==='ack')]);s.advance(10);assert.equal(r.battle.tick,0);for(const p of [a,b])p.send({type:'loaded',round:r.round});await a.next(m=>m.type==='coopState'&&m.campaign.phase==='battle'&&m.round===r.round&&m.loaded.every(Boolean));s.advance(180);assert.equal(r.campaign.wave,1);
 r.campaign.wave=9;r.battle.tick=r.campaign.nextAt;s.advance(1);for(const p of [a,b])p.send({type:'command',seq:2,action:'shopVote',value:true});await Promise.all([a.next(m=>m.type==='ack'&&m.seq===2),b.next(m=>m.type==='ack'&&m.seq===2)]);assert.equal(r.campaign.phase,'shop');const held=r.battle.tick;s.advance(20);assert.equal(r.battle.tick,held);for(const p of [a,b])p.send({type:'command',seq:3,action:'ready',value:true});await Promise.all([a.next(m=>m.type==='ack'&&m.seq===3),b.next(m=>m.type==='ack'&&m.seq===3)]);s.advance(10);assert.equal(r.battle.tick,held);for(const p of [a,b])p.send({type:'loaded',round:r.round});await a.next(m=>m.type==='coopState'&&m.round===r.round&&m.loaded.every(Boolean));s.advance(1);assert.equal(r.battle.tick,held+1);
 const third=await peer(s.port);peers.push(third);third.send({type:'auto',mode:'conquest',race:'elf'});const wt=await third.next(m=>m.type==='welcome');assert.notEqual(wt.room,wa.room);assert.equal(s.rooms.get(wt.room).campaign.mode,'conquest');
 const fourth=await peer(s.port);peers.push(fourth);fourth.send({type:'auto',mode:'endless',race:'orc'});assert.equal((await fourth.next(m=>m.type==='welcome')).room,wt.room);assert.equal(s.rooms.size,2);
 const single=await peer(s.port);peers.push(single);single.send({type:'create',mode:'soloEndless',race:'human'});const singleWelcome=await single.next(m=>m.type==='welcome'),singleRoom=s.rooms.get(singleWelcome.room);assert(singleRoom.campaign.solo);single.send({type:'command',seq:1,action:'ready',value:true});assert((await single.next(m=>m.type==='ack')).ok);assert.equal(singleRoom.campaign.phase,'battle');s.advance(10);assert.equal(singleRoom.battle.tick,0);single.send({type:'loaded',round:singleRoom.round});await single.next(m=>m.type==='coopState'&&m.status==='playing');s.advance(180);assert.equal(singleRoom.campaign.wave,1);assert.equal(singleRoom.battle.units.length,2);const intruder=await peer(s.port);peers.push(intruder);intruder.send({type:'join',room:singleWelcome.room,race:'elf'});assert.equal((await intruder.next(m=>m.type==='error')).reason,'full');singleRoom.campaign.wave=9;singleRoom.battle.tick=singleRoom.campaign.nextAt;s.advance(1);single.send({type:'command',seq:2,action:'shopVote',value:true});assert((await single.next(m=>m.type==='ack'&&m.seq===2)).ok);assert.equal(singleRoom.campaign.phase,'shop');single.send({type:'command',seq:3,action:'ready',value:true});assert((await single.next(m=>m.type==='ack'&&m.seq===3)).ok);assert.equal(singleRoom.campaign.phase,'battle');console.log('PASS real solo room: no partner needed, load barrier, half-size wave, private room and solo supply');
const pickA=await peer(s.port),pickB=await peer(s.port);peers.push(pickA,pickB);pickA.send({type:'create',mode:'endless',race:'human',chooseRace:true});const pa=await pickA.next(m=>m.type==='welcome');pickB.send({type:'auto',mode:'endless',race:'human',chooseRace:true,joinOnly:true});assert.equal((await pickB.next(m=>m.type==='welcome')).room,pa.room);pickA.send({type:'command',seq:1,action:'ready',value:true});assert.equal((await pickA.next(m=>m.type==='ack')).ok,false);pickA.send({type:'command',seq:2,action:'race',value:'elf'});assert((await pickA.next(m=>m.type==='ack'&&m.seq===2)).ok);pickB.send({type:'command',seq:1,action:'race',value:'persian'});assert((await pickB.next(m=>m.type==='ack')).ok);const picked=s.rooms.get(pa.room);assert.deepEqual(picked.pickRaces,[true,true]);assert.deepEqual(picked.campaign.armies.map(a=>a.race),['elf','persian']);assert(picked.campaign.armies.every(a=>a.gold===3000&&a.mercenaries));console.log('PASS match before race: same-mode pairing, ready blocked until both choose, independent armies');
console.log('PASS auto matching: simultaneous joins share room, waiting mode wins, full battle not joinable, load barrier and next room');
}finally{peers.forEach(p=>p.ws.terminate());await s.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
