/* Runtime faction palette and atlas portraits; original infantry motion is retained. */
(function(g){'use strict';const cache=new WeakMap(),frames=new WeakMap();
function frame(im,r){let set=frames.get(im);if(!set){set=new Map();frames.set(im,set);}const key=[r.x,r.y,r.w,r.h,r.dw,r.dh].join(',');if(set.has(key))return set.get(key);const c=document.createElement('canvas');c.width=Math.round(r.dw||r.w);c.height=Math.round(r.dh||r.h);const ctx=c.getContext('2d');ctx.drawImage(im,r.x,r.y,r.w,r.h,0,0,c.width,c.height);set.set(key,c);return c;}
function palette(im){if(cache.has(im))return cache.get(im);const c=document.createElement('canvas');c.width=im.naturalWidth||im.width;c.height=im.naturalHeight||im.height;const x=c.getContext('2d');x.drawImage(im,0,0);const pixels=x.getImageData(0,0,c.width,c.height),d=pixels.data;
 for(let i=0;i<d.length;i+=4){const r=d[i],gr=d[i+1],b=d[i+2];if(d[i+3]&&b>r*1.15&&b>gr*1.03){const light=(r+gr+b)/3;d[i]=light*.65;d[i+1]=light;d[i+2]=light*1.02;}}
 x.putImageData(pixels,0,0);cache.set(im,c);return c;}
function portrait(im,race,type){if(([105,106].includes(type)||CONTENT.nativeReinforcements?.[type])&&g.NativeSpecialVisual){NativeSpecialVisual.icon(im,race,type);return;}if(race!=='persian')return;im.onload=()=>{im.onload=null;const c=document.createElement('canvas');c.width=240;c.height=240;const x=c.getContext('2d');if(CONTENT.atlas['persian-'+type]?.fullResolution){const m=CONTENT.atlas['persian-'+type],r=m.frameRects[0],area=im.classList.contains('icon')?76:230,source=frame(im,r);const b=inkBounds(source),k=Math.min(area/b.w,area/b.h);x.drawImage(source,b.x,b.y,b.w,b.h,(240-b.w*k)/2,(240-b.h*k)/2,b.w*k,b.h*k);}else{x.drawImage(palette(im),0,0,240,240);}im.src=c.toDataURL();};}
function inkBounds(c){const a=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let l=c.width,t=c.height,r=-1,b=-1;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(a[(y*c.width+x)*4+3]>16){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y);}return r<0?{x:0,y:0,w:c.width,h:c.height}:{x:l,y:t,w:r-l+1,h:b-t+1};}
function knockFrame(race,type){return CONTENT.atlas[race+'-'+type]?.knockPose||(type===101?72:type===102?CONTENT.units[type].labels.die1:0);}
function status(ctx,x,y,scale,downed,used){if(!downed&&!used)return;ctx.save();ctx.fillStyle=downed?'#f3ce70':'#aaa5bd';ctx.font='bold '+Math.max(7,12*scale)+'px sans-serif';ctx.textAlign='center';ctx.fillText(downed?'重整 '+Math.ceil(downed/24):'◆',x,y+9);ctx.restore();}
function vitals(ctx,x,y,hp,maxHp,type){if(![103,104].includes(type)||hp<=0)return;ctx.save();ctx.fillStyle='#17201f';ctx.fillRect(x-15,y+4,30,4);ctx.fillStyle='#a9c19a';ctx.fillRect(x-14,y+5,28*Math.max(0,Math.min(1,hp/maxHp)),2);ctx.font='8px sans-serif';ctx.textAlign='center';ctx.fillStyle='#fff4c6';ctx.strokeStyle='#18201c';ctx.lineWidth=2;const text=Math.ceil(hp)+' / '+Math.ceil(maxHp);ctx.strokeText(text,x,y+17);ctx.fillText(text,x,y+17);ctx.restore();}
g.PersianArt={palette,portrait,status,vitals,frame,knockFrame};})(globalThis);
