(async()=>{'use strict';const C=CONTENT,{Battle}=Warlords,L=BATTLE_LAYOUT,canvas=document.getElementById('field'),ctx=canvas.getContext('2d'),images={},roster=C.races.persian.roster.slice(0,10);let b,benchmark=null,paused=false,last=0,acc=0;
const lane=document.getElementById('lane');for(let i=0;i<8;i++)lane.add(new Option('第 '+(i+1)+' 路',i));lane.value=3;
const files=new Set(['desert.jpg','arrow-blue.png','arrow-red.png',...Object.values(C.magicAtlas).flatMap(m=>m.files),...C.effects.human.files,...roster.flatMap(id=>C.atlas['persian-'+id].files),...[0,1,2,5].flatMap(id=>C.atlas['human-'+id].files)]);
await Promise.all([...files].map(file=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images[file]=im;resolve();};im.onerror=()=>reject(Error(file));im.src='assets/'+file;})));
function portrait(type){const im=new Image();im.alt=C.units[type].name;PersianArt.portrait(im,'persian',type);im.src='assets/icon-persian-'+type+'.png';return im;}
for(const id of roster){const button=document.createElement('button');button.append(portrait(id),document.createTextNode(C.units[id].name));const span=document.createElement('span');span.textContent=id>=101?'专属单位':'通用单位';button.append(span);button.onclick=()=>b.spawn(0,id,+lane.value,-1050);document.getElementById('cards').append(button);}
for(const id of [101,102,103,104]){const card=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p');h.textContent=C.units[id].name;p.textContent=C.units[id].description;card.append(portrait(id),h,p);document.getElementById('specials').append(card);}
function reset(){benchmark=null;b=new Battle({mode:'duel',races:['persian','human'],rosters:[roster,[0,1,2,5]],seed:932});b.spawn(0,104,3,-750);b.spawn(0,101,3,-350);b.spawn(0,2,3,-1050);b.spawn(0,103,5,-700);b.spawn(0,102,5,-250);for(const row of [3,5])for(let i=0;i<3;i++)b.spawn(1,i===1?0:1,row,250+i*220);paused=false;document.getElementById('pause').textContent='暂停';acc=0;}
function challenge(type){reset();b.units=[];b.projectiles=[];b.scores=[0,0];b.tick=0;benchmark=b.spawn(0,type,3,-300);for(let i=0;i<10;i++)b.spawn(1,1,3,300+i*70);}
document.getElementById('infantry').onclick=()=>{reset();b.units=[];b.projectiles=[];for(const [i,type]of [0,1,2].entries()){b.spawn(0,type,2+i,-500);b.spawn(1,type,2+i,500);}};
document.getElementById('tenLight').onclick=()=>challenge(103);document.getElementById('tenHeavy').onclick=()=>challenge(104);
document.getElementById('reset').onclick=reset;document.getElementById('enemy').onclick=()=>b.spawn(1,1,+lane.value,1000);document.getElementById('pause').onclick=()=>{paused=!paused;document.getElementById('pause').textContent=paused?'继续':'暂停';};document.getElementById('recovery').onclick=()=>{const u=b.spawn(0,102,+lane.value,-800);b.hurt(u,10000,{owner:1,side:1,lane:u.lane});};
function sprite(u){const row=L.lanes[u.lane],x=L.worldX(u.x,u.lane),m=u.knockFrame&&!PersianArt.knockFrame(u.race,u.type)?C.effects[u.race]:C.atlas[u.race+'-'+u.type],frame=u.downedTicks||u.knockFrame&&PersianArt.knockFrame(u.race,u.type)?(u.downedTicks?C.units[u.type].labels.die1:PersianArt.knockFrame(u.race,u.type)):u.knockFrame||u.frame,r=m.frameRects[Math.max(0,Math.min(m.frames-1,frame-1))];let im=images[m.files[r.page]];if(m.persianSkin)im=PersianArt.palette(im);ctx.save();ctx.translate(x,row.y);ctx.scale(u.dir*2*row.sx,2*row.sy);ctx.globalAlpha=u.dead?Math.max(0,Math.min(1,(224-u.ageDead)/35)):1;if(m.fullResolution){const source=PersianArt.frame(im,r);ctx.drawImage(source,r.ox,r.oy,r.dw,r.dh);}else ctx.drawImage(im,r.x,r.y,r.w,r.h,r.ox,r.oy,r.dw||r.w,r.dh||r.h);ctx.restore();if(!u.dead){ctx.fillStyle='#262424';ctx.fillRect(x-10,row.y+3,20,2);ctx.fillStyle=u.side?'#e19676':'#cab478';ctx.fillRect(x-10,row.y+3,20*u.hp/u.maxHp,2);}PersianArt.status(ctx,x,row.y,.8,u.downedTicks,u.reviveUsed);}
function render(now){const dt=last?Math.min(.15,(now-last)/1000):0;last=now;if(!paused&&b.winner===null){acc+=dt;while(acc>=1/24){b.step();acc-=1/24;}}ctx.setTransform(2,0,0,2,0,0);ctx.drawImage(images['desert.jpg'],0,0,700,500);for(let l=0;l<8;l++){for(const u of b.units.filter(u=>u.lane===l).sort((a,z)=>Number(z.dead)-Number(a.dead)||a.id-z.id))sprite(u);for(const p of b.projectiles.filter(p=>p.lane===l)){const x=L.worldX(p.x,l),y=L.lanes[l].y+p.y*L.lanes[l].sy;ctx.fillStyle=p.kind?'#e8c866':'#dfded4';ctx.fillRect(x,y,p.kind?5:8,2);}}document.getElementById('status').textContent='波斯突破 '+b.scores[0]+' · 敌方突破 '+b.scores[1]+(benchmark?' · 战象生命 '+Math.ceil(benchmark.hp)+' / '+benchmark.maxHp+(benchmark.dead?'（已击败）':''):'')+'　｜　场上 '+b.units.filter(u=>!u.dead).length+' 名单位'+(paused?' · 已暂停':'')+(b.winner!==null?' · 本轮结束，请重置':'');requestAnimationFrame(render);}
reset();requestAnimationFrame(render);
})().catch(e=>{document.getElementById('status').textContent='素材加载失败：'+e.message;console.error(e);});
