/* Original three-soldier selection composition, cached independently of battle assets. */
(()=>{'use strict';const C=CONTENT,races=Object.keys(C.races),cache=new Map(),images=new Map();let index=0,config={},busy=false,job=null;
const dialog=document.createElement('dialog');dialog.id='originalRacePicker';dialog.setAttribute('aria-labelledby','pickerTitle');dialog.innerHTML='<div class="picker-viewport"><section class="picker-stage"><h1 id="pickerTitle">选择你的种族</h1><canvas width="1400" height="1000" aria-hidden="true"></canvas><div class="picker-carousel"><button id="pickerPrev" aria-label="上一个种族">◀</button><h2 id="pickerRaceName"></h2><button id="pickerNext" aria-label="下一个种族">▶</button></div><p id="pickerDescription"></p><p id="pickerNote" role="status"></p><footer><button id="pickerBack">〈 返回</button><button id="pickerConfirm">确认种族 〉</button></footer></section></div>';document.body.append(dialog);const $=id=>dialog.querySelector('#'+id),canvas=dialog.querySelector('canvas');
new ResizeObserver(()=>dialog.querySelector('.picker-stage').style.setProperty('--picker-scale',dialog.querySelector('.picker-viewport').clientWidth/700)).observe(dialog.querySelector('.picker-viewport'));
function image(file){if(!images.has(file))images.set(file,GameAssets.image('assets/'+file).catch(e=>{images.delete(file);throw e;}));return images.get(file);}
async function build(race){if(cache.has(race))return;const target=document.createElement('canvas');target.width=1400;target.height=1000;const ctx=target.getContext('2d');ctx.scale(2,2);const parts=await Promise.all([1,5,0].map(async type=>{const m=C.atlas[race+'-'+type],f=m.frameRects[0];return {m,f,im:await image(m.files[f.page])};}));for(const [i,{m,f,im:raw}]of parts.entries()){const im=m.persianSkin?PersianArt.palette(raw):raw;ctx.save();ctx.translate(232.8+i*103.25,320);ctx.scale((i===0?-1:1)*1.3801575,1.3801575);if(m.fullResolution)ctx.drawImage(PersianArt.frame(im,f),f.ox,f.oy,f.dw,f.dh);else ctx.drawImage(im,f.x,f.y,f.w,f.h,f.ox,f.oy,f.dw||f.w,f.dh||f.h);ctx.restore();}cache.set(race,target);}
function warm(){return job??=(Promise.all(races.map(build)).catch(e=>{job=null;throw e;}));}
function render(){const race=races[index];$('pickerRaceName').textContent=C.races[race].name;$('pickerDescription').textContent=C.races[race].description;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,1400,1000);if(cache.has(race))ctx.drawImage(cache.get(race),0,0);$('pickerPrev').disabled=$('pickerNext').disabled=busy||cache.size!==races.length;$('pickerConfirm').disabled=busy||!cache.has(race);}
async function open(options={}){config=options;index=Math.max(0,races.indexOf(options.race||'human'));busy=false;$('pickerConfirm').textContent=options.confirmLabel||'确认种族 〉';$('pickerNote').textContent=cache.size===races.length?(options.note||''):'正在准备种族预览，完成后切换无需等待…';render();if(!dialog.open)dialog.showModal();try{await warm();if(!dialog.open)return;$('pickerNote').textContent=config.note||'';render();}catch{$('pickerNote').textContent='预览载入失败，请返回后重试。';}}
$('pickerPrev').onclick=()=>{index=(index+races.length-1)%races.length;render();};$('pickerNext').onclick=()=>{index=(index+1)%races.length;render();};$('pickerBack').onclick=()=>{dialog.close();config.onCancel?.();};dialog.oncancel=()=>config.onCancel?.();$('pickerConfirm').onclick=async()=>{busy=true;render();try{if(await config.onConfirm?.(races[index])!==false)dialog.close();else $('pickerNote').textContent='确认未成功，请重试。';}catch{$('pickerNote').textContent='确认未成功，请重试。';}finally{busy=false;render();}};
window.RacePicker={open,close:()=>dialog.close(),isOpen:()=>dialog.open,warm,async draw(c,race,current){await build(race);if(current()){const x=c.getContext('2d');x.setTransform(1,0,0,1,0,0);x.clearRect(0,0,c.width,c.height);x.drawImage(cache.get(race),0,0,c.width,c.height);}}};warm().catch(()=>{});
})();
