'use strict';
const assert=require('node:assert/strict'),C=require('./content.js'),P=require('./progression.js'),K=require('./campaign.js'),{Battle}=require('./engine.js');
const {packet}=require('../联机预研/room-server.cjs');let count=0;function test(name,fn){fn();console.log('PASS '+name);count++;}
function scenario(id){const [race,data]=Object.entries(C.races).find(([r,d])=>d.roster.some(t=>C.units[t].caster&&P.eligible(r,t,id))),type=data.roster.find(t=>C.units[t].caster&&P.eligible(race,t,id));const b=new Battle({mode:'duel',races:[race,'human'],rosters:[[0,1,2,5,type],[0,1,2,5]],upgrades:[{[type]:[id]},{}],seed:92}),u=b.spawn(0,type,2,-800),v=b.spawn(1,1,2,id===20?500:0);v.hp=v.maxHp=3000;b.spawn(0,0,2,-850);if(id===29){v.dead=true;v.hp=0;v.frame=C.units[1].labels.die1;}b.random=()=>.9;return {b,u,v};}
function cast(id){const x=scenario(id);assert(x.b.chooseSpell(x.u),'choose '+id);let n=0;while(!x.u.spellDone&&n++<150)x.b.stepUnit(x.u);assert(x.u.spellDone,'release '+id);assert.equal(x.u.castUses[id],1);return x;}
test('all 18 purchased spells reach their authored release and restore with cast limits',()=>{for(const id of Object.keys(C.spells).map(Number)){const {b,u}=cast(id);assert.doesNotThrow(()=>Battle.restore(b.snapshot()),'restore '+id);const a=Battle.restore(b.snapshot()),copy=Battle.restore(b.snapshot());for(let i=0;i<200;i++){a.step();copy.step();}assert.deepEqual(a.snapshot(),copy.snapshot());u.castUses[id]=C.spells[id].limit;if(id===17)u.castCount=C.spells[id].limit;assert.equal(b.chooseSpell(u),false,'limit '+id);}});
test('summons are resurrected at corpses and never recruited or put in the mercenary pool',()=>{const {b,v}=cast(29),n=b.units.find(v=>v.summoned);assert(n);assert.equal(n.x,v.x);assert.equal(n.hp,25);assert.equal(n.race,'undead');assert(v.exited);const a={...P.createArmy('human',99999),mercenaries:true};assert(!P.recruitRoster(a).includes(48));assert(!P.buyUnit(a,48));assert.doesNotThrow(()=>Battle.restore(b.snapshot()));});
test('rally buffs allies, fear retreats, disease repeats, weakness reduces damage',()=>{const rally=cast(16);assert.equal(rally.b.units.find(v=>v.type===0).specialLevel,2);const fear=cast(24),x=fear.v.x;assert(fear.v.fleeing);fear.b.stepUnit(fear.v);assert(fear.v.x>x);const sick=cast(25),hp=sick.v.hp;for(let i=0;i<3;i++)sick.b.stepUnit(sick.v);assert.equal(sick.v.hp,hp-3);const weak=cast(27);for(let i=0;i<8;i++)weak.b.stepEffects();assert(weak.v.weak);weak.v.targetId=weak.u.id;weak.u.x=weak.v.x-50;weak.b.random=()=>.5;const h=weak.u.hp;weak.b.attack(weak.v,{range:100,power:60});assert.equal(weak.u.hp,h-10);});
test('pit damages both sides once; ice, lightning, death and projectile spells resolve',()=>{const pit=cast(20),ally=pit.b.spawn(0,1,2,pit.v.x);for(let i=0;i<7;i++)pit.b.stepEffects();assert(pit.v.dead&&ally.dead);assert.equal(pit.b.players[0].kills,1);assert.equal(pit.b.players[1].kills,1);const ice=cast(18),hp=ice.v.hp;for(let i=0;i<20;i++)ice.b.stepEffects();assert.equal(ice.v.hp,hp-1000);const light=cast(14);assert(light.v.hp<3000);assert(light.v.knockFrame);const death=cast(30);assert(death.v.dead);for(const id of [28,31]){const x=cast(id);for(let i=0;i<30;i++)x.b.stepEffects();assert(x.v.hp<3000,'projectile '+id);}});
test('mind control keeps original appearance, changes team, and restores deterministically',()=>{const {b,v}=cast(26);for(let i=0;i<30;i++)b.stepEffects();assert.equal(v.side,0);assert.equal(v.owner,0);assert.equal(v.race,'human');assert.equal(v.originOwner,1);assert.equal(b.target(b.units.find(u=>u.type===0),10000),null);assert.doesNotThrow(()=>Battle.restore(b.snapshot()));const s=packet({battle:b,seats:[],code:'TEST'});assert.equal(s.units.find(u=>u[0]===v.id)[22].race,'human');});
test('anti-magic blocks targeted spells and does not remove basic bolt damage',()=>{const b=new Battle({mode:'duel',races:['human','elf'],upgrades:[{38:[30]},{1:[41]}]}),u=b.spawn(0,38,0,0),v=b.spawn(1,1,0,100);u.targetId=v.id;u.spellId=30;b.resolveSpell(u);assert(!v.dead);assert(v.resistUntil>0);u.type=3;b.fireMagic(u,'bolt');b.random=()=>.5;b.stepMagic(b.projectiles[0]);assert(Math.abs(v.hp-85)<1e-9);});
test('both cavalry types dismount at either castle side and can restore with cavalry-only rosters',()=>{for(const type of [4,6])for(const side of [0,1]){const attacker=1-side,b=new Battle({mode:'duel',races:['human','orc'],rosters:[[type],[type]],siege:{side,target:7500}}),u=b.spawn(attacker,type,0,side===1?1350:-1350);for(let i=0;i<20;i++)b.stepUnit(u);assert.equal(u.type,type===4?0:5);assert.equal(u.dismountedFrom,type);assert(b.effects.some(e=>e.key.startsWith('horse-')));assert.doesNotThrow(()=>Battle.restore(b.snapshot()));}});
test('new support runners preserve exit poses and original silhouette atlas',()=>{for(const [race,type]of [['human',100],['human2',105],['woodelf',106]]){const b=new Battle({mode:'duel',races:[race,'human'],rosters:[[type],[0]]}),u=b.spawn(0,type,0,1451);u.frame=C.units[type].labels.walk;b.stepUnit(u);assert(u.finishing);assert(u.finishedFrame);const x=u.x;b.stepUnit(u);assert.equal(u.x,x+15);assert(C.finishedAtlas[race+'-'+type]);}});
test('defense can lose territory, preserve attacker ownership, recover saves and award defeat loot',()=>{const c=K.create('human',12),castle=K.REGIONS.find(r=>r.castle&&c.owned.includes(r.id)),from=castle.adjacent.find(id=>!c.owned.includes(id));c.pendingDefense={id:castle.id,from};const b=new Battle(K.begin(c,castle.id));assert.equal(b.siege.side,0);c.battle=b.snapshot();assert.doesNotThrow(()=>K.restore(c));b.players[0].killReward=17;b.winner=1;const gold=c.army.gold,r=K.settle(c,b);assert.equal(r.reward,17);assert.equal(c.army.gold,gold+17);assert(!c.owned.includes(castle.id));assert.equal(K.territory(c,castle.id).race,K.region(from).race);assert.doesNotThrow(()=>K.restore(c));assert.equal(K.settle(c,b),null);});
test('late campaign counters are deterministic; early campaign safe; old saves migrate',()=>{const c=K.create('human',123);K.planDefense(c);assert.equal(c.pendingDefense,null);let triggered=false;for(let seed=1;seed<200;seed++){const a=K.create('human',seed);a.wins=11;const b=structuredClone(a);K.planDefense(a);K.planDefense(b);assert.deepEqual(a.pendingDefense,b.pendingDefense);if(a.pendingDefense)triggered=true;}assert(triggered);c.version=1;delete c.pendingDefense;delete c.occupiers;assert.equal(K.restore(c).version,2);});
test('authored archer kick, enchanted arrow, cursed weapon and rolling ram upgrades work',()=>{const kick=new Battle({mode:'duel',upgrades:[{2:[36]},{}]}),a=kick.spawn(0,2,0,0),v=kick.spawn(1,1,0,40);kick.random=()=>.1;kick.decide(a);assert.equal(a.frame,C.units[2].labels.kick);for(let i=0;i<3;i++)kick.stepUnit(a);assert(v.knockFrame);const curse=new Battle({mode:'duel',races:['undead','human'],upgrades:[{0:[35]},{}]}),u=curse.spawn(0,0,0,0),t=curse.spawn(1,1,0,40);u.targetId=t.id;curse.random=()=>.01;curse.attack(u,{range:100,power:60});assert(t.weak);const ram=new Battle({mode:'duel',races:['human2','human'],upgrades:[{25:[37]},{}]});assert.equal(ram.spawn(0,25,0,0).speed,10);const arrow=new Battle({mode:'duel',races:['elf','human'],upgrades:[{2:[34]},{}]}),ar=arrow.spawn(0,2,0,-100),foe=arrow.spawn(1,1,0,0);ar.targetId=foe.id;arrow.fire(ar);const shot=arrow.projectiles[0];shot.x=-10;shot.y=-66;shot.vx=20;shot.vy=0;arrow.random=()=>.01;arrow.stepUnit=()=>{};arrow.step();assert(foe.knockFrame);});
test('spell atlases and all nine caster release poses contain visible frames',()=>{for(const [race,d]of Object.entries(C.races))for(const type of d.roster.filter(t=>C.units[t].caster)){const m=C.atlas[race+'-'+type];for(const spec of Object.values(C.spells)){const r=m.frameRects[spec.frame-1];assert(spec.id===22?m.frameRects.slice(spec.frame-20,spec.frame+20).some(r=>r.w>2&&r.h>2):r.w>2&&r.h>2,race+' '+spec.id+' has empty release pose');}}assert(C.restorationAtlas.tornado.frames>1);});
test('instant death bypasses ordinary banner mitigation',()=>{const b=new Battle({mode:'duel',races:['orc','human']}),u=b.spawn(0,40,0,0),v=b.spawn(1,1,0,100);b.spawn(1,100,0,200);u.targetId=v.id;u.spellId=30;b.resolveSpell(u);assert(v.dead);});
console.log(count+' restoration checks passed.');
