/* Central menu for durable local saves and temporary server sessions. */
(function(){'use strict';
const $=id=>document.getElementById(id),dialog=$('saveSlots'),list=$('saveSlotList');
const read=(store,key)=>{try{return JSON.parse(store.getItem(key)||'null');}catch{return null;}};
const race=id=>CONTENT.races[id]?.name||'未知种族';
function slot(name,kind,detail,note,enabled,action,label='继续'){const card=document.createElement('article'),body=document.createElement('div'),title=document.createElement('h3'),tag=document.createElement('small'),progress=document.createElement('p'),help=document.createElement('p'),button=document.createElement('button');title.textContent=name;tag.textContent=kind;progress.textContent=detail;help.textContent=note;help.className='slot-note';button.textContent=enabled?label:'暂无可继续记录';button.disabled=!enabled;button.onclick=()=>{dialog.close();action();};body.append(tag,title,progress,help);card.append(body,button);list.append(card);}
function roomSlot(name,key,solo){const seat=read(sessionStorage,key),meta=read(sessionStorage,key+'-info'),exists=!!(seat?.room&&seat?.token);slot(name,'临时房间',exists?(meta?`${race(meta.race)} · ${meta.mode==='conquest'?'攻城略地':'无尽模式'} · ${meta.mode==='conquest'?meta.level:'第 '+meta.wave+' 波'} · 防线 ${meta.defense}`:'有上次房间记录'):'暂无当前标签页的房间记录','需原房间仍在运行；断线保留30秒，服务器重启后不可恢复。',exists,()=>{const url=new URL(document.querySelector('.coop-entry').href,location.href);if(solo)url.searchParams.set('solo','endless');location.href=url.href;},'尝试重连');}
$('continueMenu').onclick=()=>{list.replaceChildren();const campaign=read(localStorage,'warlords2-campaign-v1'),battle=read(localStorage,'warlords2-remake-battle-v1');slot('单人战役','本地自动存档',campaign?.army?`${race(campaign.race)} · 领土 ${campaign.owned?.length||0}/28 · ${campaign.army.gold} 黄金`:'尚未开始战役','保留征服进度、军备和已保存的当前战斗。',!!campaign?.army,()=>{$('continueCampaign').disabled=false;$('continueCampaign').click();});roomSlot('单人无尽','warlords2-solo-endless-seat-v1',true);roomSlot('双人合作','warlords2-coop-seat-v2',false);const valid=battle?.options&&['solo','watch'].includes(battle.options.mode);slot('快速野战 / 观战','本地战斗存档',valid?`${race(battle.options.races[0])} 对 ${race(battle.options.races[1])} · ${Math.floor((battle.tick||0)/24)} 秒`:'暂无可继续的野战','独立于单人战役，继续后从暂停状态开始。',!!valid,()=>{$('continueBtn').disabled=false;$('continueBtn').click();});dialog.showModal();};
})();
