(()=>{'use strict';const $=id=>document.getElementById(id),C=CONTENT,ctx=$('view').getContext('2d'),images=new Map();let b,u,v,loaded=false,paused=false,generation=0,last=0,acc=0,shots=0,observed=0;
const choices=[['human',27],['elf',24],['orc',21],['woodelf',30],['orc2',29],['undead',23],['human2',25],['troll',28],['demon',47],['persian',27]];
for(const [i,[race,type]]of choices.entries()){const o=document.createElement('option');o.value=i;o.textContent=C.races[race].name+' · '+C.units[type].name;$('unit').append(o);}
async function reset(){const token=++generation;loaded=false;const [race,type]=choices[+$('unit').value],castle=$('target').value==='castle';b=new Warlords.Battle({mode:'duel',races:[race,'human'],rosters:[[type],[1]],seed:721,...(castle?{siege:{side:1,target:7500}}:{})});const distance=C.units[type].ram?270:C.units[type].range*1.5;u=b.spawn(0,type,3,castle?1000:-distance/2);v=b.spawn(1,1,3,distance/2);v.hp=v.maxHp=100000;u.targetId=castle?-4:v.id;u.frame=C.units[type].labels.swipe1;shots=observed=0;acc=0;
const files=[...C.atlas[race+'-'+type].files,...C.atlas['human-1'].files,...(C.projectileAtlas[C.units[type].projectile]?.files||[])];try{await GameAssets.batch(files,async f=>{if(!images.has(f))images.set(f,await GameAssets.image('assets/'+f));},(n,total)=>{if(token===generation)$('status').textContent='载入 '+n+' / '+total;});if(token===generation)loaded=true;}catch(e){$('status').textContent=e.message;}}
function sprite(m,x,y,sx,sy,dir,frame,alpha=1){const r=m.frameRects[Math.max(0,Math.min(m.frames-1,frame-1))],im=images.get(m.files[r.page]);if(!im)return;ctx.save();ctx.translate(x,y);ctx.scale(dir*sx,sy);ctx.globalAlpha=alpha;ctx.drawImage(im,r.x,r.y,r.w,r.h,r.ox,r.oy,r.dw||r.w,r.dh||r.h);ctx.restore();}
function tick(){if(!loaded)return;b.events=[];if($('target').value==='troop'){if(v.knockFrame)b.stepUnit(v);else {v.x-=1.5;v.moving=true;v.speed=1.5;}}else v.dead=true;b.stepUnit(u);for(const p of b.projectiles){if(p.id>observed){shots++;observed=p.id;}b.stepSiegeProjectile(p);}b.projectiles=b.projectiles.filter(p=>!p.done);b.tick++;}
function draw(){if(!loaded)return;ctx.fillStyle='#283525';ctx.fillRect(0,0,1100,680);const m=C.atlas[u.race+'-'+u.type];sprite(m,210,275,.85,.85,1,u.frame);ctx.fillStyle='#dcdcc1';ctx.font='18px system-ui';ctx.fillText('攻击动作 · 第 '+u.frame+' 帧',380,190);ctx.fillText('累计发射 '+shots+' 枚 · 飞行 / 落地残留 '+b.projectiles.length+' 枚',380,224);ctx.strokeStyle='#7a8463';ctx.beginPath();ctx.moveTo(0,625);ctx.lineTo(1100,625);ctx.stroke();const x=n=>550+n*.32;sprite(m,x(u.x),625,.5,.5,1,u.frame);if($('target').value==='troop')sprite(C.atlas['human-1'],x(v.x),625,.5,.5,-1,1);else{ctx.fillStyle='#899480';ctx.fillRect(x(1400)-20,510,70,115);}for(const p of b.projectiles)SiegeVisual.draw(ctx,p,x(p.x),625+p.y*.25,.64,.5,sprite);$('status').textContent=`${C.units[u.type].name} · 血量 ${C.units[u.type].health} · 出兵 ${(C.units[u.type].charge/24).toFixed(2)} 秒 · 价格 ${C.units[u.type].price}\n${(b.tick/24).toFixed(2)} 秒 · 靶子累计伤害 ${(100000-v.hp).toFixed(0)} · 城堡伤害 ${Math.round(b.siege?.score||0)}`;}
function loop(t){requestAnimationFrame(loop);if(!paused&&loaded){acc+=Math.min(100,t-last)*+$('speed').value;while(acc>=1000/24){tick();acc-=1000/24;}}last=t;draw();}
$('unit').onchange=$('target').onchange=$('reset').onclick=reset;$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'播放':'暂停';};$('step').onclick=()=>{paused=true;$('pause').textContent='播放';tick();draw();};reset();requestAnimationFrame(loop);
})();
