import java.io.*;import java.nio.file.*;import java.util.*;import java.awt.image.BufferedImage;import java.awt.Graphics2D;import java.awt.RenderingHints;import java.awt.geom.AffineTransform;import javax.imageio.ImageIO;
import com.jpexs.decompiler.flash.SWF;import com.jpexs.decompiler.flash.tags.*;import com.jpexs.decompiler.flash.timeline.*;import com.jpexs.decompiler.flash.types.*;import com.jpexs.decompiler.flash.exporters.commonshape.Matrix;
/** Replace only the weapon display-list entry. Original bodies, hands, occlusion and timelines are rendered unchanged. */
public class ExportNativeWeapons {
 static Map<Integer,java.util.List<TreeMap<Integer,DepthState>>> originals=new HashMap<>();
 static void freeze(DefineSpriteTag s,int n){for(var f:s.getTimeline().getFrames())f.layers=new TreeMap<>(originals.get(s.spriteId).get(n));}
 static Matrix find(SWF swf,DepthState d,int wanted,Matrix parent,int level){if(level>4||!d.isVisible)return null;var m=parent.concatenate(new Matrix(d.matrix));if(d.characterId==wanted)return m;var c=swf.getCharacter(d.characterId);if(c instanceof DefineSpriteTag s)for(var child:s.getTimeline().getFrame(0).layers.values()){var found=find(swf,child,wanted,m,level+1);if(found!=null)return found;}return null;}
 static BufferedImage render(DefineSpriteTag s,int f,RECT rect)throws Exception{return SWF.frameToImageGet(s.getTimeline(),f,0,null,0,rect,new Matrix(),new ColorTransform(),null,1,true,0).getBufferedImage();}
 static void weapon(Graphics2D g,BufferedImage art,boolean axe){if(!axe){AffineTransform initial=g.getTransform();var shaft=art.getSubimage(380,330,130,art.getHeight()-330);g.translate(-14+(380-438)*.052,(330-1160)*.052);g.scale(.052,.052);g.drawImage(shaft,0,0,null);g.setTransform(initial);var head=art.getSubimage(200,90,600,240);g.translate(-14+(200-438)*.075,(330-1160)*.052+(90-330)*.075);g.scale(.075,.075);g.drawImage(head,0,0,null);g.setTransform(initial);}else{
  // Heavy axe uses the original axe grip and swing, including hand occlusion.
  var cropped=art.getSubimage(0,0,850,art.getHeight());g.translate(-14+605*.052,-1110*.052);g.scale(-.052,.052);g.drawImage(cropped,0,0,null);
 }}
 public static void main(String[]a)throws Exception{Locale.setDefault(Locale.US);String race=a[1];int source=Integer.parseInt(a[2]),rootId=Integer.parseInt(a[3]),weaponId=Integer.parseInt(a[4]);boolean axe=a[5].equals("axe");var swf=new SWF(new FileInputStream(a[0]),false);var art=ImageIO.read(new File(a[6]));var selectors=new ArrayList<DefineSpriteTag>();for(var c:swf.getCharacters(false).values())if(c instanceof DefineSpriteTag s&&(s.getTimeline().getFrameWithLabel("human")>=0||s.spriteId==825)){selectors.add(s);var frames=new ArrayList<TreeMap<Integer,DepthState>>();for(var f:s.getTimeline().getFrames())frames.add(new TreeMap<>(f.layers));originals.put(s.spriteId,frames);}
 for(var s:selectors){int n=s.spriteId==825?source+1:s.spriteId==348?s.getTimeline().getFrameWithLabel("blank"):s.getTimeline().getFrameWithLabel(race);if(n>=0&&n<s.getFrameCount())freeze(s,n);}
 for(int spriteId:new int[]{rootId,834,832}){var root=(DefineSpriteTag)swf.getCharacter(spriteId);var shield=(DefineSpriteTag)swf.getCharacter(348);freeze(shield,shield.getTimeline().getFrameWithLabel(spriteId!=rootId?"blank":race));RECT rect;if(spriteId==834){rect=new RECT();rect.Xmin=-3600;rect.Ymin=-3000;rect.Xmax=3600;rect.Ymax=800;}else rect=root.getRect();rect=new RECT(rect.Xmin-1600,rect.Xmax+1600,rect.Ymin-1600,rect.Ymax+1600); // Preserve fractional raster origin while expanding margins.
 File dir=new File(a[7],spriteId==834?"finished":spriteId==832?"knock":"normal");dir.mkdirs();Files.writeString(new File(dir,"origin.txt").toPath(),rect.Xmin/20.0+","+rect.Ymin/20.0);StringBuilder audit=new StringBuilder("[");
 for(int f=0;f<root.getFrameCount();f++){var frame=root.getTimeline().getFrame(f);var layers=new TreeMap<>(frame.layers);Integer depth=null;Matrix matrix=null;for(var d:layers.values()){var found=find(swf,d,weaponId,new Matrix(),0);if(found!=null){depth=d.depth;matrix=found;break;}}
 if(race.equals("troll")){File baseline=new File(new File(a[7]).getParentFile(),"troll-15/"+(spriteId==834?"finished":spriteId==832?"knock":"normal"));baseline.mkdirs();Files.writeString(new File(baseline,"origin.txt").toPath(),rect.Xmin/20.0+","+rect.Ymin/20.0);ImageIO.write(render(root,f,rect),"png",new File(baseline,(f+1)+".png"));}
 BufferedImage result;if(depth==null)result=render(root,f,rect);else{final int split=depth;frame.layers=new TreeMap<>(layers);frame.layers.entrySet().removeIf(e->e.getKey()>=split);result=render(root,f,rect);frame.layers=new TreeMap<>(layers);frame.layers.entrySet().removeIf(e->e.getKey()<=split);var foreground=render(root,f,rect);frame.layers=layers;
 var g=result.createGraphics();g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BICUBIC);g.translate(-rect.Xmin/20.0,-rect.Ymin/20.0);g.transform(new AffineTransform(matrix.scaleX,matrix.rotateSkew0,matrix.rotateSkew1,matrix.scaleY,matrix.translateX/20,matrix.translateY/20));weapon(g,art,axe);g.dispose();g=result.createGraphics();g.drawImage(foreground,0,0,null);g.dispose();}
 frame.layers=layers;ImageIO.write(result,"png",new File(dir,(f+1)+".png"));if(f>0)audit.append(',');if(matrix==null)audit.append("null");else audit.append(String.format("[%.6f,%.6f,%.6f,%.6f,%.3f,%.3f,%d]",matrix.scaleX,matrix.rotateSkew0,matrix.rotateSkew1,matrix.scaleY,matrix.translateX/20,matrix.translateY/20,depth));
 }audit.append(']');Files.writeString(new File(dir,"weapon-matrices.json").toPath(),audit);System.out.println(race+" "+dir.getName()+" "+root.getFrameCount()+" frames");}
 }
}
