from pathlib import Path
from PIL import Image
import json
import argparse
ap=argparse.ArgumentParser();ap.add_argument('frames',type=Path);ap.add_argument('--game',type=Path,default=Path(__file__).resolve().parents[1]/'种族战役2复刻');args=ap.parse_args()
root=args.game;data={}
for folder in args.frames.iterdir():
 ox,oy=map(float,(folder/'origin.txt').read_text().split(','));rects=[];pages=[];atlas=Image.new('RGBA',(2048,2048));x=y=rowh=0
 for p in sorted(folder.glob('*.png'),key=lambda p:int(p.stem)):
  im=Image.open(p).convert('RGBA');box=im.getbbox() or (0,0,2,2);box=(box[0]//2*2,box[1]//2*2,(box[2]+1)//2*2,(box[3]+1)//2*2);crop=im.crop(box)
  if x+crop.width+4>2048:x=0;y+=rowh;rowh=0
  if y+crop.height+4>2048:pages.append(atlas);atlas=Image.new('RGBA',(2048,2048));x=y=rowh=0
  atlas.paste(crop,(x+2,y+2));rects.append(dict(x=x+2,y=y+2,w=crop.width,h=crop.height,ox=ox+box[0],oy=oy+box[1],page=len(pages)));x+=crop.width+4;rowh=max(rowh,crop.height+4)
 pages.append(atlas);files=[];sizes=[]
 for i,page in enumerate(pages):
  name=f'restore-{folder.name}-{i}.png';files.append(name);box=page.getbbox() or (0,0,2,2);page=page.crop((0,0,(box[2]+3)//2*2,(box[3]+3)//2*2));sizes.append(dict(file=name,width=page.width,height=page.height));page.save(root/'assets'/name);page.resize((page.width//2,page.height//2),Image.Resampling.LANCZOS).save(root/'assets/mobile'/name)
 data[folder.name]=dict(frames=len(rects),files=files,pages=sizes,frameRects=rects)
js='/* Original SWF effect and utility atlases; generated by tools/ExportRestoration.java. */\n(function(g){function apply(C){C.restorationAtlas='+json.dumps(data,separators=(',',':'))+';for(const [k,m]of Object.entries(C.restorationAtlas))C.atlas["restore-"+k]=m;for(const [k,m]of Object.entries(C.restorationAtlas))if(k.startsWith("mage-"))C.atlas[k.slice(5)]=m;C.atlas["undead-48"]=C.restorationAtlas["undead-48"];if(C.finishedAtlas)C.finishedAtlas["human-100"]=C.restorationAtlas["finish-human-100"];\n}if(typeof module!=="undefined")module.exports=apply;else apply(g.CONTENT);})(globalThis);\n'
(root/'restoration-atlas.js').write_text(js,encoding='utf-8')
print(len(data),'packed restoration atlases')
